# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 07:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_preference', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=user_profile.models.credential_photo_upload_loc, verbose_name='Image Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_learns', models.CharField(max_length=60, null=True)),
                ('requester_teaches', models.CharField(max_length=60, null=True)),
                ('pending', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('staff_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn1', models.CharField(blank=True, max_length=54, null=True, verbose_name='Learn A')),
                ('learn2', models.CharField(blank=True, max_length=54, null=True, verbose_name='Learn B')),
                ('learn3', models.CharField(blank=True, max_length=54, null=True, verbose_name='Learn C')),
                ('teach1', models.CharField(blank=True, max_length=54, null=True, verbose_name='Teach A')),
                ('teach2', models.CharField(blank=True, max_length=54, null=True, verbose_name='Teach B')),
                ('teach3', models.CharField(blank=True, max_length=54, null=True, verbose_name='Teach C')),
                ('introduction', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Introduction')),
                ('profile_photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=user_profile.models.profile_photo_upload_loc, verbose_name='Profile Image', width_field='width_field')),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_profile_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_edit_profile', 'Can edit own profile'),),
            },
        ),
        migrations.AddField(
            model_name='pair',
            name='accepter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_accepter', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='pair',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_requester', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='credentialimage',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='credentialimage', to='user_profile.Profile'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='user_profile.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='pair',
            unique_together=set([('requester', 'accepter')]),
        ),
    ]
